from __future__ import annotations


CANONICAL_OPERATOR_PREFERENCES_NAMESPACE = "skeleton.operator_preferences"
CANONICAL_OPERATOR_PREFERENCES_GATEWAY_NAMESPACE = "skeleton"
CANONICAL_OPERATOR_PREFERENCES_SCOPE = "global_operator_working_style"
FAST_AUTONOMOUS_EXECUTION_KEY = "fast_autonomous_execution_v1"
OPERATOR_WORKING_STYLE_RECORD_TYPE = "operator_working_style_preference"
