from __future__ import annotations

from enum import StrEnum


class FailureClass(StrEnum):
    EXECUTOR_UNAVAILABLE = "EXECUTOR_UNAVAILABLE"
    EXECUTOR_AUTH_UNAVAILABLE = "EXECUTOR_AUTH_UNAVAILABLE"
    MODEL_QUOTA = "MODEL_QUOTA"
    MODEL_PROVIDER_OUTAGE = "MODEL_PROVIDER_OUTAGE"
    MODEL_UNSUPPORTED = "MODEL_UNSUPPORTED"
    TOOLCHAIN_CAPABILITY_MISMATCH = "TOOLCHAIN_CAPABILITY_MISMATCH"
    NO_PROGRESS = "NO_PROGRESS"
    DELIVERABLE_MISSING = "DELIVERABLE_MISSING"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    TRANSIENT_IO = "TRANSIENT_IO"
    POLICY_DENIED = "POLICY_DENIED"
    BUDGET_EXHAUSTED = "BUDGET_EXHAUSTED"
    PRIVACY_DENIED = "PRIVACY_DENIED"
    AMBIGUOUS_SIDE_EFFECT = "AMBIGUOUS_SIDE_EFFECT"


STABLE_FAILURE_CLASSES = frozenset(item.value for item in FailureClass)
