from __future__ import annotations

from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path
import json
import re
from typing import Any, Iterable, Mapping

import yaml
from jsonschema import Draft202012Validator


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_REGISTRY_PATH = ROOT / "policies" / "RULE_ENFORCEMENT_REGISTRY.yaml"
DEFAULT_SCHEMA_PATH = ROOT / "schemas" / "rule_enforcement_registry.schema.json"

RUNTIME_ENFORCEMENTS = frozenset({"runtime_gate", "preflight_gate"})
ACTION_APPROVAL_PREFIX = "exact_"
PRIVATE_REPORT_PATTERNS = (
    re.compile(r"/home/agent/"),
    re.compile(r"/(?:root|etc|var|mnt|media|run/secrets)(?:/|\\b)"),
    re.compile(r"[A-Za-z]:\\\\Users\\\\"),
    re.compile(r"\b[A-Za-z0-9_]*(?:token|secret|password|api[_-]?key)[A-Za-z0-9_]*\s*[:=]\s*\S+", re.IGNORECASE),
    re.compile(r"SKELETON_TG_[A-Z0-9_]+"),
    re.compile(r"raw payload", re.IGNORECASE),
    re.compile(r"environment value", re.IGNORECASE),
)


@dataclass(frozen=True)
class RegistryValidationResult:
    errors: tuple[str, ...]
    lifecycle_counts: tuple[tuple[str, int], ...]
    enforcement_counts: tuple[tuple[str, int], ...]
    coverage_counts: tuple[tuple[str, int], ...]
    active_rules_lacking_enforcement: tuple[str, ...]
    duplicate_rule_ids: tuple[str, ...]
    contradictory_rules: tuple[tuple[str, str], ...]
    superseded_rules: tuple[str, ...]

    @property
    def ok(self) -> bool:
        return not self.errors


def load_registry(path: Path | str = DEFAULT_REGISTRY_PATH) -> dict[str, Any]:
    data = yaml.safe_load(Path(path).read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError("rule enforcement registry must be a mapping")
    return data


def load_schema(path: Path | str = DEFAULT_SCHEMA_PATH) -> dict[str, Any]:
    data = json.loads(Path(path).read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError("rule enforcement registry schema must be a mapping")
    return data


def validate_registry(
    registry: Mapping[str, Any] | None = None,
    *,
    root: Path | str = ROOT,
    schema: Mapping[str, Any] | None = None,
) -> RegistryValidationResult:
    root_path = Path(root)
    data = dict(registry or load_registry(root_path / "policies" / "RULE_ENFORCEMENT_REGISTRY.yaml"))
    schema_data = dict(schema or load_schema(root_path / "schemas" / "rule_enforcement_registry.schema.json"))

    errors: list[str] = []
    validator = Draft202012Validator(schema_data)
    for error in sorted(validator.iter_errors(data), key=lambda item: list(item.path)):
        location = ".".join(str(part) for part in error.path) or "<root>"
        errors.append(f"{location}: {error.message}")

    rules = _mapping_items(data.get("rules"))
    source_coverage = _mapping_items(data.get("source_coverage"))
    rule_ids = tuple(str(rule.get("rule_id", "")) for rule in rules)
    duplicate_ids = _duplicates(rule_ids)
    errors.extend(f"duplicate rule_id: {rule_id}" for rule_id in duplicate_ids)

    errors.extend(_missing_file_errors(root_path, source_coverage, "source_coverage"))
    errors.extend(_missing_file_errors(root_path, rules, "rule"))
    errors.extend(_coverage_errors(rules, source_coverage))

    active_none = tuple(
        str(rule["rule_id"])
        for rule in rules
        if rule.get("lifecycle") == "active" and rule.get("enforcement") == "none"
    )
    errors.extend(
        f"active rule uses enforcement=none: {rule_id}"
        for rule_id in active_none
    )

    errors.extend(_gate_metadata_errors(rules))
    errors.extend(_approval_scope_errors(rules))
    contradictions = _contradictory_active_rules(rules)
    errors.extend(
        f"contradictory active rules: {left} vs {right}"
        for left, right in contradictions
    )
    errors.extend(_supersession_reference_errors(rules))

    return RegistryValidationResult(
        errors=tuple(errors),
        lifecycle_counts=_sorted_counts(rule.get("lifecycle") for rule in rules),
        enforcement_counts=_sorted_counts(rule.get("enforcement") for rule in rules),
        coverage_counts=_sorted_counts(item.get("classification") for item in source_coverage),
        active_rules_lacking_enforcement=active_none,
        duplicate_rule_ids=duplicate_ids,
        contradictory_rules=contradictions,
        superseded_rules=tuple(
            sorted(str(rule["rule_id"]) for rule in rules if rule.get("lifecycle") == "superseded")
        ),
    )


def build_report(
    registry: Mapping[str, Any] | None = None,
    *,
    root: Path | str = ROOT,
) -> str:
    root_path = Path(root)
    data = dict(registry or load_registry(root_path / "policies" / "RULE_ENFORCEMENT_REGISTRY.yaml"))
    result = validate_registry(data, root=root_path)
    rules = _mapping_items(data.get("rules"))

    lines = [
        "# Rule Enforcement Matrix",
        "",
        "Generated by `scripts/generate_rule_enforcement_report.py`. Do not hand-edit.",
        "",
        "Stage 0 is inventory-only: no merge, runtime activation, canon promotion, provider call, deployment, service restart, or Skeleton/Jeeves boundary change is enabled by this report.",
        "",
        "References: " + ", ".join(sorted(data.get("issue_refs", []), key=_issue_sort_key)),
        "",
        "## Counts",
        "",
        "Lifecycle counts:",
        "",
    ]
    lines.extend(_count_lines(result.lifecycle_counts))
    lines.extend(["", "Enforcement counts:", ""])
    lines.extend(_count_lines(result.enforcement_counts))
    lines.extend(["", "Source coverage counts:", ""])
    lines.extend(_count_lines(result.coverage_counts))

    lines.extend(["", "## Enforcement Gaps", ""])
    lines.extend(_id_lines(result.active_rules_lacking_enforcement))

    lines.extend(["", "## Duplicates Contradictions Superseded", ""])
    duplicate_sources = _source_ids_by_classification(data, "duplicated")
    lines.append("- duplicated_source_count: " + str(len(duplicate_sources)))
    lines.append("- duplicate_rule_ids: " + _inline_values(result.duplicate_rule_ids))
    lines.append("- contradictory_active_rule_pairs: " + _inline_pairs(result.contradictory_rules))
    lines.append("- superseded_rule_ids: " + _inline_values(result.superseded_rules))

    lines.extend(["", "## Rule Inventory", ""])
    for rule in sorted(rules, key=lambda item: str(item["rule_id"])):
        lines.append(
            "- `{rule_id}` lifecycle={lifecycle} enforcement={enforcement} owner={owner}".format(
                rule_id=rule["rule_id"],
                lifecycle=rule["lifecycle"],
                enforcement=rule["enforcement"],
                owner=rule["owner_component"],
            )
        )

    lines.extend(["", "## Next Stages", ""])
    for stage in data.get("next_stages", []):
        lines.append(f"- `{stage['stage']}`: {stage['goal']}")

    lines.extend(["", "## Validation", ""])
    if result.ok:
        lines.append("- status: ok")
    else:
        lines.append("- status: failed")
        lines.append("- error_count: " + str(len(result.errors)))

    report = "\n".join(lines) + "\n"
    leaked = public_report_violations(report)
    if leaked:
        raise ValueError("generated rule enforcement report contains private or unsafe terms: " + ", ".join(leaked))
    return report


def public_report_violations(report: str) -> tuple[str, ...]:
    found: list[str] = []
    for pattern in PRIVATE_REPORT_PATTERNS:
        if pattern.search(report):
            found.append(pattern.pattern)
    return tuple(found)


def _mapping_items(value: object) -> list[dict[str, Any]]:
    if not isinstance(value, list):
        return []
    return [item for item in value if isinstance(item, dict)]


def _duplicates(values: Iterable[str]) -> tuple[str, ...]:
    counts = Counter(values)
    return tuple(sorted(value for value, count in counts.items() if value and count > 1))


def _missing_file_errors(root: Path, items: Iterable[Mapping[str, Any]], label: str) -> list[str]:
    errors: list[str] = []
    for item in items:
        source_file = item.get("source_file")
        if not isinstance(source_file, str):
            continue
        path = root / source_file
        if not path.exists():
            item_id = item.get("rule_id", source_file)
            errors.append(f"{label} references missing file for {item_id}: {source_file}")
    return errors


def _coverage_errors(
    rules: Iterable[Mapping[str, Any]],
    source_coverage: Iterable[Mapping[str, Any]],
) -> list[str]:
    covered = {item.get("source_file") for item in source_coverage}
    missing = sorted(
        {
            str(rule.get("source_file"))
            for rule in rules
            if isinstance(rule.get("source_file"), str) and rule.get("source_file") not in covered
        }
    )
    return [f"rule source lacks source_coverage entry: {source_file}" for source_file in missing]


def _gate_metadata_errors(rules: Iterable[Mapping[str, Any]]) -> list[str]:
    errors: list[str] = []
    for rule in rules:
        if rule.get("enforcement") not in RUNTIME_ENFORCEMENTS:
            continue
        rule_id = str(rule.get("rule_id", "<unknown>"))
        if not str(rule.get("gate_entrypoint", "")).strip():
            errors.append(f"{rule_id} runtime/preflight rule lacks gate_entrypoint")
        reason_tokens = rule.get("reason_tokens")
        if not isinstance(reason_tokens, list) or not reason_tokens:
            errors.append(f"{rule_id} runtime/preflight rule lacks stable reason token")
    return errors


def _approval_scope_errors(rules: Iterable[Mapping[str, Any]]) -> list[str]:
    errors: list[str] = []
    for rule in rules:
        protected_actions = rule.get("protected_actions")
        if not isinstance(protected_actions, list) or not protected_actions:
            continue
        approval_scope = rule.get("approval_scope")
        if not isinstance(approval_scope, str) or not approval_scope.startswith(ACTION_APPROVAL_PREFIX):
            errors.append(f"{rule.get('rule_id', '<unknown>')} protected action lacks exact approval_scope")
    return errors


def _contradictory_active_rules(rules: Iterable[Mapping[str, Any]]) -> tuple[tuple[str, str], ...]:
    grouped: dict[tuple[str, tuple[str, ...], str], list[Mapping[str, Any]]] = defaultdict(list)
    for rule in rules:
        if rule.get("lifecycle") != "active":
            continue
        actions = tuple(sorted(str(action) for action in rule.get("protected_actions", []) if isinstance(action, str)))
        if not actions:
            continue
        key = (str(rule.get("owner_component")), actions, str(rule.get("approval_scope")))
        grouped[key].append(rule)

    pairs: set[tuple[str, str]] = set()
    for grouped_rules in grouped.values():
        for index, left in enumerate(grouped_rules):
            for right in grouped_rules[index + 1:]:
                left_id = str(left.get("rule_id"))
                right_id = str(right.get("rule_id"))
                if _related_by_supersession(left, right):
                    continue
                if (
                    left.get("enforcement") != right.get("enforcement")
                    or left.get("gate_entrypoint") != right.get("gate_entrypoint")
                    or left.get("public_private_boundary") != right.get("public_private_boundary")
                ):
                    pairs.add(tuple(sorted((left_id, right_id))))
    return tuple(sorted(pairs))


def _related_by_supersession(left: Mapping[str, Any], right: Mapping[str, Any]) -> bool:
    left_id = str(left.get("rule_id"))
    right_id = str(right.get("rule_id"))
    left_supersedes = set(left.get("supersedes", []) if isinstance(left.get("supersedes"), list) else [])
    left_superseded_by = set(left.get("superseded_by", []) if isinstance(left.get("superseded_by"), list) else [])
    right_supersedes = set(right.get("supersedes", []) if isinstance(right.get("supersedes"), list) else [])
    right_superseded_by = set(right.get("superseded_by", []) if isinstance(right.get("superseded_by"), list) else [])
    return (
        right_id in left_supersedes
        or right_id in left_superseded_by
        or left_id in right_supersedes
        or left_id in right_superseded_by
    )


def _supersession_reference_errors(rules: Iterable[Mapping[str, Any]]) -> list[str]:
    rule_list = list(rules)
    ids = {str(rule.get("rule_id")) for rule in rule_list}
    errors: list[str] = []
    for rule in rule_list:
        rule_id = str(rule.get("rule_id", "<unknown>"))
        for field in ("supersedes", "superseded_by"):
            values = rule.get(field)
            if not isinstance(values, list):
                continue
            for value in values:
                if value not in ids:
                    errors.append(f"{rule_id} {field} unknown rule_id: {value}")
    return errors


def _sorted_counts(values: Iterable[object]) -> tuple[tuple[str, int], ...]:
    counts = Counter(str(value) for value in values if value is not None)
    return tuple(sorted(counts.items()))


def _count_lines(counts: Iterable[tuple[str, int]]) -> list[str]:
    return [f"- {key}: {value}" for key, value in counts]


def _id_lines(values: Iterable[str]) -> list[str]:
    value_tuple = tuple(values)
    if not value_tuple:
        return ["- none"]
    return [f"- `{value}`" for value in value_tuple]


def _inline_values(values: Iterable[str]) -> str:
    value_tuple = tuple(values)
    return "none" if not value_tuple else ", ".join(f"`{value}`" for value in value_tuple)


def _inline_pairs(values: Iterable[tuple[str, str]]) -> str:
    value_tuple = tuple(values)
    if not value_tuple:
        return "none"
    return ", ".join(f"`{left}`/`{right}`" for left, right in value_tuple)


def _source_ids_by_classification(data: Mapping[str, Any], classification: str) -> tuple[str, ...]:
    return tuple(
        sorted(
            str(item["source_file"])
            for item in _mapping_items(data.get("source_coverage"))
            if item.get("classification") == classification
        )
    )


def _issue_sort_key(value: object) -> int:
    text = str(value).lstrip("#")
    return int(text) if text.isdigit() else 0
