from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import yaml


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "docs" / "NOTEBOOKLM_SOURCEPACK.md"


CANONICAL_QUICK_ANSWERS = [
    (
        "Runner Queue Workflow",
        "A Runner task starts as a GitHub issue labeled `runner:ready`; the systemd timer picks it up; "
        "the Runner moves it to `runner:running`; Codex runs in the checkout with the `workspace-write` "
        "sandbox; the Runner posts a `DONE` or `BLOCKED` report; the final label becomes `runner:done` "
        "or `runner:blocked`; Telegram sends the completion notification."
    ),
    (
        "Operator Lockout While Running",
        "While an issue is `runner:running`, the operator must not run: `git checkout`, `git pull`, "
        "`git reset`, `pytest`, `rm` cleanup, or `systemctl restart`."
    ),
    (
        "Skeleton/Jeeves Boundary",
        "Skeleton is the controlled construction and control layer. Jeeves is a separate future assistant "
        "product and runtime. Skeleton builds and governs work but is not Jeeves; Jeeves is not a Skeleton "
        "runtime adapter."
    ),
    (
        "NotebookLM Authority",
        "NotebookLM is advisory. GitHub remains canon for source files, issues, pull requests, labels, "
        "runner state, and merge history."
    ),
]


def load_yaml(path: Path) -> dict[str, Any]:
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8").strip()


def bullet_list(items: list[str]) -> list[str]:
    if not items:
        return ["- None recorded."]
    return [f"- {item}" for item in items]


def capability_line(capability_id: str, capability: dict[str, Any]) -> str:
    module = capability.get("module", "unspecified")
    tested = capability.get("tested")
    tested_text = "tested" if tested is True else "not tested" if tested is False else "test status unspecified"
    description = capability.get("description", "No description recorded.")
    return f"- `{capability_id}`: {description} Module: `{module}`. Status: {tested_text}."


def build_sourcepack(root: Path = ROOT) -> str:
    boot = load_yaml(root / "BOOT_MANIFEST.yaml")
    registry = load_yaml(root / "CAPABILITY_REGISTRY.yaml")
    project_index = load_yaml(root / "PROJECT_INDEX.yaml")
    runner_setup = read_text(root / "scripts" / "README_RUNNER_SETUP.md")
    runner_status = read_text(root / "docs" / "RUNNER_QUEUE_STATUS.md")

    capabilities = registry["capabilities"]
    available_capabilities = [
        capability_line(capability_id, capability)
        for capability_id, capability in capabilities.items()
        if capability["status"] == "available"
    ]
    planned_capabilities = [
        capability_line(capability_id, capability)
        for capability_id, capability in capabilities.items()
        if capability["status"] == "planned"
    ]

    lines: list[str] = [
        "# NotebookLM Sourcepack",
        "",
        "This document is generated by `scripts/build_notebooklm_sourcepack.py` from local repository files.",
        "Do not hand-edit this file; update the source manifests or docs and regenerate it.",
        "",
        "## Canon Note",
        "",
        "NotebookLM is a mirror for reading and synthesis only. GitHub is canon for source files, issues, pull requests, labels, runner state, and merge history.",
        "This sourcepack makes no live Google calls, no NotebookLM API calls, and includes no secrets.",
        "",
        "## Canonical Quick Answers",
        "",
    ]
    for question, answer in CANONICAL_QUICK_ANSWERS:
        lines.extend([f"### {question}", "", answer, ""])

    lines.extend(
        [
            "## Source Inputs",
            "",
            "- `BOOT_MANIFEST.yaml`",
            "- `CAPABILITY_REGISTRY.yaml`",
            "- `PROJECT_INDEX.yaml`",
            "- `projects/*/STATE.yaml`",
            "- `scripts/README_RUNNER_SETUP.md`",
            "- `docs/RUNNER_QUEUE_STATUS.md`",
            "",
            "## Boot Entrypoint",
            "",
            f"- Repository: `{boot['repo']}`",
            f"- Ref: `{boot['ref']}`",
            f"- Entrypoint: `{boot['entrypoint']}`",
            f"- Status: `{boot['status']}`",
            "",
            "Boot read order:",
            "",
        ]
    )
    lines.extend(f"- `{source}`" for source in boot["read_order"])
    lines.extend(
        [
            "",
            "Boot output required fields:",
            "",
        ]
    )
    lines.extend(f"- `{field}`" for field in boot["boot_output"]["required_fields"])
    lines.extend(
        [
            "",
            "## Available Capabilities",
            "",
        ]
    )
    lines.extend(available_capabilities or ["- None recorded."])
    lines.extend(
        [
            "",
            "## Planned Capabilities",
            "",
        ]
    )
    lines.extend(planned_capabilities or ["- None recorded."])
    lines.extend(
        [
            "",
            "## Project States",
            "",
        ]
    )

    for project_id, spec in project_index["projects"].items():
        state_path = root / "projects" / project_id / "STATE.yaml"
        state = load_yaml(state_path)
        lines.extend(
            [
                f"### {project_id}",
                "",
                f"- Means: {spec['means']}",
                f"- Repo: `{spec['repo']}`",
                f"- Entrypoint: `{spec['entrypoint']}`",
                f"- State file: `projects/{project_id}/STATE.yaml`",
                f"- Status: `{state['status']}`",
                f"- State role: `{state['state_role']}`",
                f"- Last verified: `{state['last_verified']}`",
                f"- Evidence source: {state['evidence_source']}",
                "",
                "Summary:",
                "",
            ]
        )
        lines.extend(bullet_list(state.get("summary", [])))
        lines.extend(["", "Next actions:", ""])
        lines.extend(bullet_list(state.get("next_actions", [])))
        lines.append("")

    lines.extend(
        [
            "## Runner Queue Status",
            "",
            "The current runner queue status is mirrored below from `docs/RUNNER_QUEUE_STATUS.md`.",
            "",
            "```markdown",
            runner_status,
            "```",
            "",
            "## Runner Setup Reference",
            "",
            "The runner setup reference is mirrored below from `scripts/README_RUNNER_SETUP.md`.",
            "",
            "```markdown",
            runner_setup,
            "```",
            "",
            "## Next Safe Steps",
            "",
            "- Refresh this sourcepack only from the local repository checkout.",
            "- Run `python3 scripts/build_notebooklm_sourcepack.py` after approved manifest, project state, or runner-status changes.",
            "- Review `git diff -- docs/NOTEBOOKLM_SOURCEPACK.md` before copying the generated document into Google Docs or NotebookLM.",
            "- Keep secrets, private project data, environment files, credentials, and live API outputs out of the sourcepack.",
            "- Treat NotebookLM answers as advisory summaries; verify implementation decisions against GitHub canon before changing code.",
            "",
        ]
    )
    return "\n".join(lines)


def write_sourcepack(root: Path = ROOT, output: Path = DEFAULT_OUTPUT) -> Path:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build_sourcepack(root), encoding="utf-8")
    return output


def main() -> int:
    parser = argparse.ArgumentParser(description="Build the local NotebookLM sourcepack.")
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Output Markdown path. Defaults to docs/NOTEBOOKLM_SOURCEPACK.md.",
    )
    args = parser.parse_args()
    output = args.output if args.output.is_absolute() else ROOT / args.output
    written = write_sourcepack(ROOT, output)
    print(f"wrote {written.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
