from __future__ import annotations

CONTRACTS = (
    "SOURCE_ENTITY",
    "NORMALIZED_SEGMENT",
    "SIMPLIFICATION_EVIDENCE",
    "ROOM_GEOMETRY_CANDIDATE",
    "ACCEPTED_ROOM_SHELL",
    "ORDERED_WALL_SEGMENT",
    "ROOM_ZONE_GRAPH",
    "GEOMETRY_CAPABILITY_REPORT",
    "GEOMETRY_RESULT_MANIFEST",
)

ACCEPTED = "ACCEPTED"
REVIEW_REQUIRED = "REVIEW_REQUIRED"
UNIT_M = "m"
DEFAULT_TOLERANCE_MM = 5.0
AREA_REPORT_M2 = 0.1
MATERIAL_AREA_DELTA_M2 = 0.05
